import { Actor } from '../models/Actor.ts';

export const actors: Actor[] = [
  {
    id: 1,
    name: 'Emma Thompson',
    imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
    location: 'London, UK',
    specialties: ['Drama', 'Period Drama', 'Comedy'],
    experience: 15,
    rating: 4.9,
    availability: 'Next week',
    bio: 'Award-winning actress specializing in dramatic roles and period pieces',
  },
  {
    id: 2,
    name: 'Michael Chen',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
    location: 'Los Angeles, USA',
    specialties: ['Action', 'Martial Arts', 'Drama'],
    experience: 8,
    rating: 4.7,
    availability: 'This week',
    bio: 'Versatile actor with extensive martial arts training',
  },
  {
    id: 3,
    name: 'Sofia Rodriguez',
    imageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
    location: 'Madrid, Spain',
    specialties: ['Theater', 'Musical', 'Voice Acting'],
    experience: 12,
    rating: 4.8,
    availability: 'Next month',
    bio: 'Theater veteran with a powerful singing voice',
  },
  {
    id: 4,
    name: 'James Wilson',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
    location: 'New York, USA',
    specialties: ['Method Acting', 'Theater', 'Film'],
    experience: 20,
    rating: 5.0,
    availability: 'Next week',
    bio: 'Method actor with extensive Broadway experience',
  },
  {
    id: 5,
    name: 'Aisha Patel',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb',
    location: 'Mumbai, India',
    specialties: ['Bollywood', 'Contemporary', 'Dance'],
    experience: 10,
    rating: 4.6,
    availability: 'This week',
    bio: 'Versatile performer with classical dance training',
  },
  {
    id: 6,
    name: 'Lucas Schmidt',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d',
    location: 'Berlin, Germany',
    specialties: ['Independent Film', 'Experimental', 'Voice Acting'],
    experience: 7,
    rating: 4.5,
    availability: 'Next month',
    bio: 'Independent film specialist with unique artistic vision',
  },
];
